name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        target: thumbv7em-none-eabihf
        toolchain: nightly
        override: true
    - name: Build
      run: cargo build --target thumbv7em-none-eabihf --verbose 
    - name: Run tests
      run: cargo test --target thumbv7em-none-eabihf --verbose
