name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup target add thumbv7em-none-eabihf
    - run: rustup override set nightly
    - name: Build
      run: cargo build --target thumbv7em-none-eabihf --verbose 
    - name: Run tests
      run: cargo test --target thumbv7em-none-eabihf --verbose
